### PR TITLE
reworked backend

### PR DESCRIPTION
**Pull request by Johann150**
Did a major rework on the backend. There is more info in the new README.md

The client is very much not done. The current concept would be to show the players with normal HTML objects and some fancy CSS. This is not fixed now, but the backend interface should hopefully be mostly done.

### CODE REVIEW

**Comment by Johann150** [comment]
Player rendering is working now. Changing positions and messages are updated across different clients.

**Comment by Johann150** [comment]
@stedn Are you planning on doing anything with this? Because otherwise I'd close this PR.

**Comment by stedn** [comment]
Oh wow, I'm so sorry. I must have missed this. Thank you so much. I will look it over tonight.

**Review by stedn — COMMENTED** [review]
The reason that the backend was using firebase was because that allowed deploying with a realtime database for free.  These changes would make it significantly more costly for someone to deploy.

Is there any way to make this deployable on firebase's infrastructure with some of the changes to make it easier to work with?

**Comment by Johann150** [comment]
I'm not 100% sure any more, but I think i wrote it in such a way that there is no database involved at all. It still works because the individual players report their position back regularly which is then broadcast by the server again. So the server would not know where a specific person is except when handling that information. This means that a database / firebase is not necessary with this setup.

I am not sure though how doable it is to send this information over the network repeatedly.

If you want to reinstate firebase nevertheless, I will probably not be much help as I have no experience with it. That might also be something that can be added in after merging. I would also not be willing to put in the effort to learn firebase for this PR.

**Pull request closed without merging**
